### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by tachyons** [ankane/active_hll#3]
We have been investigating HLL for [circuitverse](https://github.com/CircuitVerse/CircuitVerse/) to enable page views without storing users' visit details. Our main blocker with Postgres-based HLL is that it is difficult to set up locally for windows, Linux and Mac with beginner-friendly installation. I know it is too much to ask, Just wondering does this gem have any plan to support a fallback mechanism when the Postgres extension is not present.

**Comment by ankane** [comment]
Hey @tachyons, sounds like a good use case. There aren't plans to support a fallback, but you could probably build something similar around Redis.
